### ISSUE TITLE
DispatchQueue error

### ISSUE THREAD

**Issue by Tejkaran** [RickRedSix/BLE4.0-iOS-Swift-Demo#1]
Hi

I have an issue in these lines

```
        //stop scanning after 3 seconds
        DispatchQueue.main.after(when: .now() + 3.0) {
            self.stopScanForBLEDevices()
        }
```

it says that:
Value of type 'Dispatch queue' has no member 'after'

is there someway around this?
This comes up when i download your version. I am using swift 3/xcode 8

**Comment by MiguelAngelBrav** [comment]
@Tejkaran, the solution is:

```
DispatchQueue.main.asyncAfter(deadline: .now() + SCAN_PERIOD) {
      self.stopScanForBLEDevices()
}
```
I hope to help you

**Comment by RickRedSix** [comment]
@Tejkaran Sorry for the late reply, completely missed this.

@MiguelAngelBrav Thanks for the solution, looks like this was changed in the new updates. I have pushed a commit (c3ea9a74f7d398f709a59514da598981f292dde8) to fix this issue.
