### ISSUE TITLE
didDiscoverCharacteristicsFor not called

### ISSUE THREAD

**Issue by pradeepktg** [RickRedSix/BLE4.0-iOS-Swift-Demo#5]
Hi Rick, App is crashing while trying to send "Hello World" message and didDiscoverCharacteristicsFor method is not called and hence mainCharacteristic is nil. Any reason why didDiscoverCharacteristicsFor is not being called?

I'm trying to communicate/send/write value using UART Service (esp-wroom-32d)

**Comment by RickRedSix** [comment]
Hi @pradeepktg, 

Is didDiscoverServices being called? As it should discover the services and then if it finds a service with a UUID of "180A", "1800" or "DFB0". The last one is specific to the Bluno board I used for the demo. If it finds these, it will then try to discover the characteristics of one of those services, when those are found it will call didDiscoverCharacteristicsFor. So you could try changing the UUID's to what your development board is broadcasting.

**Comment by pradeepktg** [comment]
Thank you. I missed the delegate part and it is working now. Closing this issue. But do you have any good document for creating and managing CentralManager singleton class?
